### PR TITLE
chore: prettierrc

### PR DESCRIPTION
**Pull request by Warrior-X**

### CODE REVIEW

**Comment by CameronCT** [comment]
#1 

Also, we should make it so the code is auto-formatted on save and make all files follow prettier format.

**Comment by Warrior-X** [comment]
I think that option is for VSCode, not Prettier (I can’t find any option for that in the Prettier docs)

**Comment by Warrior-X** [comment]
Do you want to write a CI GitHub workflow to automatically run it on push?

**Comment by CameronCT** [comment]
We can do that too, I was more just thinking to just include the updated files in this PR and push. Prettier should be automatically active when working on the project, but whatever you prefer.

**Comment by Warrior-X** [comment]
Just formatted everything

**Comment by CameronCT** [comment]
Ty, going to be pushing an update from `redesign` branch (no idea why I'm still using it to be fair) and then merging with main then I will merge this over.

**Pull request merged**
